version: "3.8"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /media/plex_library/:/config
      - /media/plex_library/music/:/music
      - /media/plex_library/tv/:/tv
      - /media/plex_library/movies/:/movies
    restart: unless-stopped