volumes:
  portainer_data:
    driver: local

services:
###NETWORK
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9080:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: '${PIHOLE_PW}'
      DNSMASQ_LISTENING: 'all'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1' #cloudflare
      FTLCONF_LOCAL_IPV4: '192.168.1.244'
      DNSSEC: 'true'
      FTLCONF_MAXDBDAYS: 180
    volumes:
      - '${DATA_DIR}/etc-pihole:/etc/pihole'
      - '${DATA_DIR}/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - '8765:80'
    volumes:
      - "${DATA_DIR}/speedtest/config:/config"
    environment:
      TZ: 'America/New_York'
      OOKLA_EULA_GDPR: 'true'
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped

###MEDIA
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${DATA_DIR}/plex/:/config
      - ${MEDIA_DIR}/music/:/music
      - ${MEDIA_DIR}/tv/:/tv
      - ${MEDIA_DIR}/movies/:/movies
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${DATA_DIR}/jellyfin/:/config
      - ${MEDIA_DIR}/tv/:/data/tvshows
      - ${MEDIA_DIR}/movies/:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  kiwix-wikipedia:
      image: ghcr.io/kiwix/kiwix-serve:latest
      volumes:
        - ${MEDIA_DIR}/wikipedia_zim:/data
      ports:
        - 8181:8080
      command:
        - '*.zim'
      restart: unless-stopped

  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - ${DATA_DIR}/emulatorjs/config:/config
      - ${DATA_DIR}/emulatorjs/data:/data
      - ${MEDIA_DIR}/roms/gb:/data/gb/roms
    ports:
      - 3000:3000
      - 1180:80
    restart: unless-stopped

###HOME
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    volumes:
      - ${DATA_DIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/:/host:ro
    restart: unless-stopped
    privileged: true

  homebridge:
    image: homebridge/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - HOMEBRIDGE_CONFIG_UI=1
    volumes:
      - ${DATA_DIR}/homebridge:/homebridge

###ETC
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
    - "18080:80"
    volumes:
    - ${DATA_DIR}/nginx/website:/usr/share/nginx/html

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_DIR}/portainer:/data"
    restart: always

  scrutiny:
    # https://github.com/AnalogJ/scrutiny
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "18181:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${DATA_DIR}/scrutiny/config:/opt/scrutiny/config
      - ${DATA_DIR}/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"






