version: "3.8"
#test
volumes:
  portainer_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
    - "18080:80"
    volumes:
    - ${DATA_DIR}/nginx/website:/usr/share/nginx/html
  
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_DIR}/portainer_data:/data"
    restart: always