- hosts: localhost
  connection: local
  become: true

  tasks:
  
#--- set timezone ---
  - name: set timezone to NY
    timezone:
      name: America/New_York

#--- system update + upgrade ---
  - name: apt update
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: full
      state: latest

#--- install core packages ---
  - name: install core packages
    apt:
      name: 
        - htop
        - tmux
        - nmap
        - wget
        - python3-pip
        - nano
        - lm-sensors
        - rclone
        - fish
        - curl
        - tree
        - vim
        - smartmontools
        - unzip
        - sysstat
        - net-tools
        - neofetch
      state: latest

#--- install docker ---
  - name: install required docker packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
      state: latest
  
  - name: add docker gpg apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repo to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present 
  
  - name: install docker and docker-compose
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io  
        - docker-compose-plugin
      state: latest
  
  - name: create docker group
    group:
      name: docker
      state: present

  - name: add user to docker group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes
      state: present

#--- install syncthing ---
  - name: add syncthing repo to apt
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing stable
      state: present 
  
  - name: add syncthing pgp apt key
    apt_key:
      url: https://syncthing.net/release-key.txt
      state: present

  - name: install syncthing
    apt:
      name:
        - syncthing
      state: latest

  - name: Enable syncthing service
    ansible.builtin.systemd:
      name: "syncthing@{{ user }}.service"
      enabled: true
      masked: no
  
  - name: Start syncthing service
    service:
      name: "syncthing"
      state: "started"
      enabled: true

#--- configure git ---
  - name: set git user
    git_config:
      name: user.name
      scope: global
      value: "Ryan LaLiberty"
      state: present
    become_user: "{{ user }}"

  - name: set git email
    git_config:
      name: user.email
      scope: global
      value: "rycolos@gkserver.net"
      state: present
    become_user: "{{ user }}"

  - name: set git editor
    git_config:
      name: core.editor
      scope: global
      value: nano
      state: present
    become_user: "{{ user }}"

#--- assorted config ---
  - name: set default shell to fish
    user:
      name: "{{ user }}"
      shell: /usr/bin/fish
      state: present

#--- create directories and mount points ---
  - name: create dir for logs
    file:
      path: "/home/{{ user }}/logs"
      mode: 0775
      owner: "{{ user }}"
      group: "{{ user }}"
      state: directory

  - name: create backup hdd mount point
    file:
      path: "/media/backup_main"
      mode: 0775
      owner: "{{ user }}"
      group: "{{ user }}"
      state: directory
 
  - name: create plex hdd mount point
    file:
      path: "/media/plex_library"
      mode: 0775
      owner: "{{ user }}"
      group: "{{ user }}"
      state: directory

  - name: create ext backup mount point
    file:
      path: "/media/backup2_ext"
      mode: 0775
      owner: "{{ user }}"
      group: "{{ user }}"
      state: directory

#--- clone gkserver repo for utilities and config
  - name: clone gkserver-config repo
    git:
      repo: https://github.com/rycolos/gkserver-config.git
      dest: /home/{{ user }}/gkserver
    become_user: "{{ user }}"

#--- create cronjobs ---
  - name: cron - retention policy
    cron:
      name: "retention policy - sat 2am"
      minute: "0"
      hour: "2"
      weekday: "5"
      job: /home/{{ user }}/gkserver/scripts/trash_clean.sh && echo "/home/{{ user }}/gkserver/scripts/trash_clean.sh" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present

  - name: cron - music library backup
    cron:
      name: "music library backup - sun 12am"
      minute: "0"
      hour: "0"
      weekday: "0"
      job: /home/{{ user }}/gkserver/scripts/plex_gkserver_backup.sh && echo "/home/{{ user }}/gkserver/scripts/plex_gkserver_backup.sh" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present

  - name: cron - home to backup_main
    cron:
      name: "home to backup_main - daily 2am"
      minute: "0"
      hour: "2"
      job: /home/{{ user }}/gkserver/scripts/home_gkserver_backup.sh && echo "/home/{{ user }}/gkserver/scripts/home_gkserver_backup.sh" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py

  - name: cron - docker-data to backup_main
    cron:
      name: "docker-data to backup_main - daily 3am"
      minute: "0"
      hour: "3"
      job: /home/{{ user }}/gkserver/scripts/docker_gkserver_backup.sh && echo "/home/{{ user }}/gkserver/scripts/docker_gkserver_backup.sh" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present

  - name: cron - backup_main to gdrive
    cron:
      name: "backup_main to gdrive - sun 2am"
      minute: "0"
      hour: "2"
      weekday: "6"
      job: /home/{{ user }}/gkserver/scripts/gdrive_gkserver_backup.sh && echo "/home/{{ user }}/gkserver/scripts/gdrive_gkserver_backup.sh" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present

  - name: cron - backup_main test
    cron:
      name: "backup_main hdd test - 18th of the month"
      minute: "0"
      hour: "0"
      day: "18"
      job: /usr/sbin/smartctl --test=long /dev/sda &> /dev/null
      state: present

  - name: cron - backup_main report
    cron:
      name: "backup_main hdd report - 20th of the month"
      minute: "0"
      hour: "0"
      day: "20"
      job: /usr/sbin/smartctl -a /dev/sda >> /home/{{ user }}/logs/hdd_ext1_report.log && echo "/usr/sbin/smartctl -a /dev/sda" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present

  - name: cron - plex_library test
    cron:
      name: "plex_library hdd test - 22nd of the month"
      minute: "0"
      hour: "0"
      day: "22"
      job: /usr/sbin/smartctl --test=long /dev/sdb &> /dev/null
      state: present

  - name: cron - plex_library report
    cron:
      name: "plex_library hdd report - 24th of the month"
      minute: "0"
      hour: "0"
      day: "24"
      job: /usr/sbin/smartctl -a /dev/sdb >> /home/{{ user }}/logs/hdd_ext2_report.log && echo "/usr/sbin/smartctl -a /dev/sdb" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present

  - name: cron - summarize backup logs
    cron:
      name: "summarize backup logs - daily 4am"
      minute: "0"
      hour: "4"
      job: tail -n 5 /home/{{ user }}/logs/*_backup.log > /home/{{user}}/logs/summary.log && echo "tail -n 5 /home/{{ user }}/logs/*_backup.log > /home/{{user}}/logs/summary.log" | python3 /home/{{ user }}/gkserver/scripts/discord-pipe.py
      state: present
