name: compose up

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker-compose/*__docker-compose.yml'

jobs:
  compose:
    runs-on: self-hosted
    steps:
      - name: up
        run: |
          cd ~/gkserver/docker-compose
          docker compose up -d --remove-orphans \
          -f etc__docker-compose.yml
          -f home__docker-compose.yml
          -f media__docker-compose.yml
          -f network__docker-compose.yml