name: compose up

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker-compose/docker-compose.yml'

jobs:
  compose:
    runs-on: self-hosted
    steps:
      - name: up
        run: |
          cd ~/gkserver-machine/docker-compose
          docker compose up -d --remove-orphans