name: Pull and Docker Compose

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: pull
        run: |
          cd ~/gkserver-machine
          git pull origin main

  compose:
    runs-on: self-hosted
    steps:
      - name: up
        run: |
          cd ~/gkserver-machine
          echo "hey" > ~/logs/run.log
      