name: remote pull

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: pull
        run: |
          cd ~/gkserver
          git pull origin main
      